import { ILogger } from './Logger.interface';

/**
 * Options for the trace
 * @param attributes Additional attributes to add to each span generated by the methods of the class
 * @param logger Logger to use for debugging logs
 */
export interface TraceWrapperOptions {
  attributes?: Record<string, string>;
  logger?: ILogger;
}
